import React from 'react';
import {View, Text, StyleSheet} from 'react-native';
import ImageWithBoundingBox from './imageBox';

const ResultScreen = ({route}) => {
  const {img, title} = route.params;
  return (
    <View style={styles.container}>
      <View>{title && <Text style={styles.title}>{title} Report</Text>}</View>
      {/* Part 1 */}
      <View style={styles.contentContainer}>
        {img?.image && (
          <ImageWithBoundingBox
            image={img.image}
            imageSize={img.imageSize}
            predictions={img.predictions}
          />
        )}
      </View>
      {/* Part 2 */}
      <View style={styles.contentContainer}>
        <Text style={styles.resultText}>
          This result is generated by a machine learning model for reference
          only. If you feel unwell, please consult a professional or seek
          medical attention promptly.
        </Text>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#d1d8c2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  square: {
    width: '80%',
    aspectRatio: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: 12,
  },
  contentContainer: {
    width: '80%',
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: 12,
    padding: 10,
    marginTop: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#666',
  },
  questionText: {
    color: '#666',
    textAlign: 'left',
  },
  resultText: {
    color: '#666',
    textAlign: 'left',
  },
});

export default ResultScreen;
